/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125752-g2f209337fc-20260724"
#endif /* AVUTIL_FFVERSION_H */
