name: linter
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'adefossez/demucs' || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.10"
        enable-cache: true
        cache-dependency-glob: pyproject.toml

    - name: Install dependencies
      run: uv sync --extra train

    - name: Run linter
      run: make linter
